//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SA44_Team10A_SportsFacBookingSystem
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTransaction
    {
        public int TransactionId { get; set; }
        public int MemberId { get; set; }
        public int FacilityId { get; set; }
        public System.DateTime SlotTime { get; set; }
        public string Status { get; set; }
        public System.DateTime TransactionDate { get; set; }
    
        public virtual Facility Facility { get; set; }
        public virtual Member Member { get; set; }
    }
}
